MusicWorld/Models/Catalogs/CatalogsAddSongViewModel.cs
using MusicWorld.Models.Songs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsAddSongViewModel
    {


        public string CatalogId { get; set; }

        public string SongId { get; set; }

        public ICollection<SongsViewModel> Songs { get; set; }

    }
}

MusicWorld/Models/Catalogs/CatalogsAllViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsAllViewModel
    {
        public ICollection<CatalogsViewModel> Catalogs { get; set; }

        public string SearchWord { get; set; }
    }
}

MusicWorld/Models/Catalogs/CatalogsCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsCreateViewModel
    {

        [Required]
        [MaxLength(64, ErrorMessage = "Name length should be no more than 64 characters!")]
        public string Name { get; set; }

        [Required]
        [MaxLength(255, ErrorMessage = "Name length should be no more than 255 characters!")]
        public string Descritpion { get; set; }

        [Required]
        public string MyUser_UserName { get; set; }

    }
}

MusicWorld/Models/Catalogs/CatalogsDetailViewModel.cs
using MusicWorld.Models.Songs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsDetailViewModel
    {

        public CatalogsViewModel CatalogInformation { get; set; }

        public ICollection<SongsViewModel> NotAddedSongs { get; set; }

        public ICollection<SongsViewModel> CurrentCatalogSongs { get; set; }

    }
}

MusicWorld/Models/Catalogs/CatalogsEditViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsEditViewModel
    {
        public string Id { get; set; }

        [Required]
        [MaxLength(64, ErrorMessage = "Name length should be no more than 64 characters!")]
        public string Name { get; set; }

        [Required]
        [MaxLength(255, ErrorMessage = "Name length should be no more than 255 characters!")]
        public string Descritpion { get; set; }

    }
}

MusicWorld/Models/Catalogs/CatalogsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorld.Models.Catalogs
{
    public class CatalogsViewModel
    {

        public string Id { get; set; }

        public string Name { get; set; }

        public string Descritpion { get; set; }

        public string MyUserId { get; set; }

        [Display(Name = "Username")]
        public string MyUserName { get; set; }

        public int SongsCount { get; set; }

    }
}

MusicWorld/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicWorld.Data;
using MusicWorld.Data.Entity;
using MusicWorld.Models.Catalogs;
using MusicWorld.Models.Songs;

namespace MusicWorld.Controllers
{
    public class CatalogController : Controller
    {

        private readonly MusicWorldDbContext _dbContext;
        private readonly UserManager<MyUser> _userManager;

        public CatalogController(MusicWorldDbContext dbContext, UserManager<MyUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }


        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> Index(string searchName = "")
        {

            var allCatalogs = _dbContext.Catalogs.ToList();
            var model = new CatalogsAllViewModel()
            {
                Catalogs = new List<CatalogsViewModel>()
            };

            if (!CheckWhetherCurrentUserIsAdmin())
            {
                allCatalogs = allCatalogs.Where(x => x.MyUserId == GetCurrentUserId()).ToList();
            }

            if (searchName != null && searchName != "")
            {
                allCatalogs = allCatalogs.Where(x => x.Name.Contains(searchName)).ToList();
            }

            

            foreach (var catalog in allCatalogs)
            {

                int songsCount = _dbContext.CatalogSong.Where(x => x.CatalogId == catalog.Id).Count();

                var singleViewModel = new CatalogsViewModel()
                {
                    Id = catalog.Id,
                    Name = catalog.Name,
                    Descritpion = catalog.Description,
                    MyUserId = catalog.MyUserId,
                    MyUserName = (await _dbContext.Users.FindAsync(catalog.MyUserId)).UserName,
                    SongsCount = songsCount
                };

                model.Catalogs.Add(singleViewModel);

            }

            return View(model);

        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Index(SongsAllViewModel model)
        {
            return await this.Index(model.SearchWord);
        }


        [Authorize]
        public async Task<IActionResult> Details(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var catalog = await _dbContext.Catalogs.FindAsync(id);

            if (catalog == null)
            {
                return NotFound();
            }

            var model = new CatalogsDetailViewModel();

            model.CatalogInformation = new CatalogsViewModel()
            {
                Id = catalog.Id,
                Name = catalog.Name,
                Descritpion = catalog.Description,
                MyUserId = catalog.MyUserId,
                MyUserName = (await _dbContext.Users.FindAsync(catalog.MyUserId)).UserName
            };

            var allSongs = _dbContext.Songs;
            var allAviableSongs = allSongs;
            var currentUserId = _userManager.GetUserId(HttpContext.User);
            var currentCatalogAllSongs = _dbContext.CatalogSong.Where(x => x.CatalogId == id).ToList();

            model.CurrentCatalogSongs = new List<SongsViewModel>();
            model.NotAddedSongs = new List<SongsViewModel>();

            foreach (var song in allSongs)
            {
                if (currentCatalogAllSongs.Any(x => x.SongId == song.Id))
                {
                    var singleViewModel = new SongsViewModel()
                    {
                        Id = song.Id,
                        Name = song.Name,
                        Duration = FormatDuration(song.DurationSeconds),
                        AlbumId = song.AlbumId,
                        PerformerId = song.PerformerId,
                        AlbumName = (await _dbContext.Albums.FindAsync(song.AlbumId)).Name,
                        PerformerName = (await _dbContext.Performers.FindAsync(song.PerformerId)).Name
                    };

                    model.CurrentCatalogSongs.Add(singleViewModel);
                }
                else
                {
                    var singleViewModel = new SongsViewModel()
                    {
                        Id = song.Id,
                        Name = song.Name,
                        Duration = FormatDuration(song.DurationSeconds),
                        AlbumId = song.AlbumId,
                        PerformerId = song.PerformerId,
                        AlbumName = (await _dbContext.Albums.FindAsync(song.AlbumId)).Name,
                        PerformerName = (await _dbContext.Performers.FindAsync(song.PerformerId)).Name
                    };

                    model.NotAddedSongs.Add(singleViewModel);
                }



            }

            return View(model);

        }


        [Authorize]
        public IActionResult Create()
        {
            var model = new CatalogsCreateViewModel();
            return View(model);
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CatalogsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var catalog = new Catalog()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = model.Name,
                    Description = model.Descritpion,
                    MyUserId = _dbContext.Users.Where(x => x.NormalizedUserName == model.MyUser_UserName.ToUpper()).FirstOrDefault().Id
                };

                await _dbContext.Catalogs.AddAsync(catalog);
                await _dbContext.SaveChangesAsync();

                return Redirect("/Catalog");

            }
            return View(model);
        }


        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var catalog = await _dbContext.Catalogs.FindAsync(id);

            if (catalog == null)
            {
                return NotFound();
            }

            var model = new CatalogsEditViewModel()
            {
                Id = catalog.Id,
                Name = catalog.Name,
                Descritpion = catalog.Description,
            };

            return View(model);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(CatalogsEditViewModel model)
        {

            if (ModelState.IsValid)
            {

                var catalog = _dbContext.Catalogs.Find(model.Id);

                catalog.Name = model.Name;
                catalog.Description = model.Descritpion;

                try
                {
                    _dbContext.Catalogs.Update(catalog);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContext.Catalogs.Any(e => e.Id == catalog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }

                return Redirect("/Catalog");

            }

            return View(model);

        }


        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirm(string id)
        {

            var catalog = await _dbContext.Catalogs.FindAsync(id);

            try
            {
                _dbContext.Catalogs.Remove(catalog);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_dbContext.Catalogs.Any(e => e.Id == catalog.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }

            return RedirectToAction(nameof(Index));

        }


        [Authorize]
        public async Task<IActionResult> AddSongToCatalog(string catalogId, string songId)
        {
            bool isAuthorized = CheckWhetherCatalogBelongsToCurrentUser(catalogId) || CheckWhetherCurrentUserIsAdmin();
            if (!isAuthorized)
            {
                // Alarm
                // A non-admin user made an attempt to change someone else's catalog information
                return NotFound();
            }

            var catalogSong = new CatalogSong()
            {
                CatalogId = catalogId,
                SongId = songId
            };

            if (_dbContext.CatalogSong.Any(x => x == catalogSong))
            {
                // Alarm
                // An authorized user made an attempt to add to their catalog dublicate song entity
                return Redirect($"Catalog/Details/{catalogId}");
            }

            try
            {
                await _dbContext.CatalogSong.AddAsync(catalogSong);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_dbContext.Catalogs.Any(e => e.Id == catalogId) ||
                    !_dbContext.Songs.Any(e => e.Id == songId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }

            return Redirect($"/Catalog/Details/{catalogId}");

MusicWorld/Views/Catalog/Create.cshtml
@model MusicWorld.Models.Catalogs.CatalogsCreateViewModel

@{
    ViewData["Title"] = "Create catalog";
}

<h1>Create new catalog</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MyUser_UserName" value="@this.User.Identity.Name" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descritpion" class="control-label"></label>
                <input asp-for="Descritpion" class="form-control" />
                <span asp-validation-for="Descritpion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MusicWorld/Views/Catalog/Delete.cshtml
@model MusicWorld.Models.Catalogs.CatalogsDetailViewModel

@{
    ViewData["Title"] = "Delete catalog";
}

<h3>Are you sure you want to delete this catalog?</h3>

<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatalogInformation.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.Name)
        </dd>
        <dt class="col-sm-2">
            Created by
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.MyUserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatalogInformation.Descritpion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.Descritpion)
        </dd>
        <dt class="col-sm-2">
            Songs:
        </dt>
        <dd class="col-sm-10">
            @foreach (var song in Model.CurrentCatalogSongs)
            {
                <p>@song.Name (@song.Duration min) - by @song.PerformerName</p>
            }
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.CatalogInformation.Id" />
        <input type="submit" value="Delete" class="btn btn-danger font-weight-bold mr-3 p-2" />
        <a type="submit" asp-action="Index" class="btn btn-info p-2">Cancel</a>
    </form>
</div>

MusicWorld/Views/Catalog/Details.cshtml
@model MusicWorld.Models.Catalogs.CatalogsDetailViewModel

@{
    ViewData["Title"] = "Detail catalog";
}

<h1>Catalog information</h1>

<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatalogInformation.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatalogInformation.MyUserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.MyUserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatalogInformation.Descritpion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatalogInformation.Descritpion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CatalogInformation.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<br />
<br />

<h1>This catalog's songs</h1>

<table class="table text-center">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Duration
            </th>
            <th>
                From album
            </th>
            <th>
                Created by
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.CurrentCatalogSongs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AlbumName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PerformerName)
                </td>
                <td>
                    <a asp-controller="Catalog" asp-action="RemoveSongFromCatalog" asp-route-catalogId="@Model.CatalogInformation.Id" asp-route-songId="@item.Id">remove song from catalog</a>
                </td>
            </tr>
        }


    </tbody>
</table>

<br />
<br />
<h1>Add other songs to this catalog</h1>

<table class="table text-center">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Duration
            </th>
            <th>
                From album
            </th>
            <th>
                Created by
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.NotAddedSongs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AlbumName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PerformerName)
                </td>
                <td>
                    <a asp-controller="Catalog" asp-action="AddSongToCatalog" asp-route-catalogId="@Model.CatalogInformation.Id" asp-route-songId="@item.Id">add song to catalog</a>
                </td>
            </tr>
        }


    </tbody>
</table>

MusicWorld/Views/Catalog/Edit.cshtml
@model MusicWorld.Models.Catalogs.CatalogsEditViewModel

@{
    ViewData["Title"] = "Edit catalog";
}

<h1>Edit catalog</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descritpion" class="control-label"></label>
                <input asp-for="Descritpion" class="form-control" />
                <span asp-validation-for="Descritpion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MusicWorld/Views/Catalog/Index.cshtml
@model MusicWorld.Models.Catalogs.CatalogsAllViewModel

@{
    ViewData["Title"] = "Index";
}


@if (this.User.IsInRole("Admin"))
{
    <h1>All catalogs</h1>

}
else if (this.User.IsInRole("User"))
{
    <h1>Your catalogs</h1>

}

<p>
    <a asp-action="Create">Create new catalog</a>
</p>


<form asp-action="Index">
    <div class="row">
        <div class="col-md-4">
            <input asp-for="SearchWord" placeholder="Search catalog ..." class="form-control" />
        </div>
        <div class="col-md-1">
            <input type="submit" value="Search" class="btn btn-info" />
        </div>

    </div>
</form>

<br />

@if (Model.Catalogs != null && Model.Catalogs.Count != 0)
{

    <table class="table text-center">
        <thead>
            <tr>
                <th>
                    Catalog name
                </th>
                <th>
                    Username
                </th>
                <th>
                    Count of songs
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Catalogs)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MyUserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SongsCount)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <div class="text-center text-black-50 font-italic w-10" style="font:40px Arial">Nothing to display</div>
}