MusicWorld/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWorld.Data;
using MusicWorld.Data.Entity;
using MusicWorld.Models.Albums;
using MusicWorld.Models.Songs;

namespace MusicWorld.Controllers
{
    public class AlbumController : Controller
    {

        private readonly MusicWorldDbContext _dbContext;

        public AlbumController(MusicWorldDbContext dbContext)
        {
            _dbContext = dbContext;
        }


        [Authorize]
        public async Task<IActionResult> Index(string searchName)
        {

            var allAlbums = _dbContext.Albums.ToList();
            allAlbums = allAlbums.OrderBy(x => x.Name).ToList();

            if (searchName != null && searchName != "")
            {
                allAlbums = allAlbums.Where(x => x.Name.Contains(searchName)).ToList();
            }

            var model = new AlbumsAllViewModel()
            {
                Albums = new List<AlbumsViewModel>()
            };



            foreach (var album in allAlbums)
            {

                int songNumber = _dbContext.Songs.Where(x => x.AlbumId == album.Id).Count();
                string performerName = (await _dbContext.Performers.FindAsync(album.PerformerId)).Name;

                var singleViewModel = new AlbumsViewModel()
                {
                    Id = album.Id,
                    Name = album.Name,
                    PerformerId = album.PerformerId,
                    PerformerName = performerName,
                    SongsNumber = songNumber
                };

                model.Albums.Add(singleViewModel);

            }

            return View(model);

        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Index(SongsAllViewModel model)
        {
            return await this.Index(model.SearchWord);
        }


        [Authorize]
        public async Task<IActionResult> Details(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var album = await _dbContext.Albums.FindAsync(id);

            if (album == null)
            {
                return NotFound();
            }

            var songsVM = new List<SongsViewModel>();

            foreach (var song in _dbContext.Songs.Where(x => x.AlbumId == id))
            {
                var singleSongVM = new SongsViewModel()
                {
                    Id = song.Id,
                    Name = song.Name,
                    Duration = FormatDuration(song.DurationSeconds)
                };
                songsVM.Add(singleSongVM);
            }

            var model = new AlbumsDetailViewModel
            {
                AlbumInformation = new AlbumsViewModel()
                {
                    Id = album.Id,
                    Name = album.Name,
                    PerformerId = album.PerformerId,
                    PerformerName = (await _dbContext.Performers.FindAsync(album.PerformerId)).Name,
                    DateOfRelease = album.DateOfRelease,
                    SongsNumber = 0
                },
                Songs = songsVM
            };

            return View(model);

        }


        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var model = new AlbumsCreateViewModel();
            model.DateOfRelease = DateTime.Now;
            CreateSelectListForPerformers();
            return View(model);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(AlbumsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var album = new Album()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = model.Name,
                    PerformerId = model.PerformerId,
                    DateOfRelease = model.DateOfRelease ?? DateTime.Now
                };

                await _dbContext.Albums.AddAsync(album);
                await _dbContext.SaveChangesAsync();

                return Redirect("/Album");

            }
            return View(model);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var album = await _dbContext.Albums.FindAsync(id);

            if (album == null)
            {
                return NotFound();
            }

            var model = new AlbumsEditViewModel()
            {
                Id = album.Id,
                Name = album.Name,
                PerformerId = album.PerformerId,
                DateOfRelease = album.DateOfRelease
            };

            return View(model);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(AlbumsEditViewModel model)
        {

            if (ModelState.IsValid)
            {

                var album = _dbContext.Albums.Find(model.Id);

                album.Name = model.Name;
                album.PerformerId = model.PerformerId;

                if (model.DateOfRelease != null)
                {
                    album.DateOfRelease = model.DateOfRelease.Value;
                }

                try
                {
                    _dbContext.Albums.Update(album);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContext.Albums.Any(e => e.Id == album.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }

                return Redirect("/Album");

            }

            return View(model);

        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var album = await _dbContext.Albums.FindAsync(id);

            if (album == null)
            {
                return NotFound();
            }

            var model = new AlbumsViewModel()
            {
                Id = album.Id,
                Name = album.Name,
                PerformerId = album.PerformerId,
                PerformerName = (await _dbContext.Performers.FindAsync(album.PerformerId)).Name,
                DateOfRelease = album.DateOfRelease
            };

            return View(model);

        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {

            var album = await _dbContext.Albums.FindAsync(id);

            try
            {
                _dbContext.Albums.Remove(album);
                await _dbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_dbContext.Albums.Any(e => e.Id == album.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

            }

            return RedirectToAction(nameof(Index));
        }


        private string FormatDuration(int durationSeconds)
        {
            int min = durationSeconds / 60;
            int sec = durationSeconds % 60;

            string res =
                ((min < 10) ? "0" : "") + min + ":" +
                ((sec < 10) ? "0" : "") + sec;

            return res;
        }


        private void CreateSelectListForPerformers(string selectedAlbumId = "")
        {



            if (selectedAlbumId == null || selectedAlbumId == "")
            {
                ViewData["PerformerId"] = new SelectList(_dbContext.Performers, "Id", "Name");
            }
            else
            {
                ViewData["PerformerId"] = new SelectList(_dbContext.Performers, "Id", "Name", selectedAlbumId);
            }



        }

    }
}

MusicWorld/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWorld.Data;
using MusicWorld.Data.Entity;
using MusicWorld.Models.Songs;

namespace MusicWorld.Controllers
{
    public class SongController : Controller
    {
        private readonly MusicWorldDbContext _dbContext;

        public SongController(MusicWorldDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        // GET: Song
        [Authorize]
        public async Task<IActionResult> Index(string searchName = "")
        {

            var allSongs = _dbContext.Songs.ToList();
            allSongs = allSongs.OrderBy(x => x.Name).ToList();

            if (searchName != null && searchName != "")
            {
                allSongs = allSongs.Where(x => x.Name.Contains(searchName)).ToList();
            }

            var model = new SongsAllViewModel()
            {
                Songs = new List<SongsViewModel>()
            };

            foreach (var song in allSongs)
            {

                var singleViewModel = new SongsViewModel()
                {
                    Id = song.Id,
                    Name = song.Name,
                    Duration = FormatDuration(song.DurationSeconds),
                    AlbumId = song.AlbumId,
                    PerformerId = song.PerformerId,
                    AlbumName = (await _dbContext.Albums.FindAsync(song.AlbumId)).Name,
                    PerformerName = (await _dbContext.Performers.FindAsync(song.PerformerId)).Name,
                };

                model.Songs.Add(singleViewModel);

            }

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Index(SongsAllViewModel model)
        {
            return await this.Index(model.SearchWord);
        }

        // GET: Song/Details/5
        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = (await _dbContext.Songs.FindAsync(id));

            if (song == null)
            {
                return NotFound();
            }

            var model = new SongsDetailViewModel();

            model.SongInformation = new SongsViewModel()
            {
                Id = song.Id,
                Name = song.Name,
                Duration = FormatDuration(song.DurationSeconds),
                AlbumId = song.AlbumId,
                PerformerId = song.PerformerId,
                AlbumName = (await _dbContext.Albums.FindAsync(song.AlbumId)).Name,
                PerformerName = (await _dbContext.Performers.FindAsync(song.PerformerId)).Name
            };

            return View(model);
        }

        // GET: Song/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var model = new SongsCreateViewModel();
            CreateSelectListForAlbums();
            return View(model);
        }

        // POST: Song/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(SongsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {

                int seconds = (model.DurationMinutes * 60 + model.DurationSeconds);

                if (seconds <= 0)
                {
                    model.ErrorMessages.Add("Duration should be at least 1 second");
                    CreateSelectListForAlbums(model.AlbumId);
                    return View(model);
                }

                var song = new Song()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = model.Name,
                    AlbumId = model.AlbumId,
                    DurationSeconds = (model.DurationMinutes * 60 + model.DurationSeconds),
                    PerformerId = _dbContext.Albums.Find(model.AlbumId).PerformerId
                };

                await _dbContext.Songs.AddAsync(song);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }

            CreateSelectListForAlbums(model.AlbumId);

            return View(model);
        }

        // GET: Song/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _dbContext.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            var model = new SongsEditViewModel()
            {
                Id = song.Id,
                Name = song.Name,
                DurationMinutes = (song.DurationSeconds / 60),
                DurationSeconds = (song.DurationSeconds % 60)
            };

            CreateSelectListForAlbums(model.AlbumId);

            return View(model);
        }

        // POST: Song/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(SongsEditViewModel model)
        {
            if (ModelState.IsValid)
            {

                var song = _dbContext.Songs.Find(model.Id);

                song.Name = model.Name;
                song.AlbumId = model.AlbumId;
                song.PerformerId = _dbContext.Albums.Find(model.AlbumId).PerformerId;
                song.DurationSeconds = (model.DurationMinutes * 60 + model.DurationSeconds);

                try
                {
                    _dbContext.Songs.Update(song);
                    await _dbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_dbContext.Songs.Any(e => e.Id == song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }

                return Redirect("/Song");

            }

            CreateSelectListForAlbums(model.AlbumId);

            return View(model);
        }

        // GET: Song/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var song = await _dbContext.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            var model = new SongsViewModel()
            {
                Id = song.Id,
                Name = song.Name,
                Duration = FormatDuration(song.DurationSeconds),
                AlbumId = song.AlbumId,
                PerformerId = song.PerformerId,
                AlbumName = (await _dbContext.Albums.FindAsync(song.AlbumId)).Name,
                PerformerName = (await _dbContext.Performers.FindAsync(song.PerformerId)).Name
            };

            return View(model);
        }

        // POST: Song/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var song = await _dbContext.Songs.FindAsync(id);

            if (song == null)
            {
                return NotFound();
            }

            _dbContext.Songs.Remove(song);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private string FormatDuration(int durationSeconds)
        {
            int min = durationSeconds / 60;
            int sec = durationSeconds % 60;

            string res =
                ((min < 10) ? "0" : "") + min + ":" +
                ((sec < 10) ? "0" : "") + sec;

            return res;
        }

        private void CreateSelectListForAlbums(string selectedAlbumId = "")
        {

            var resSelectList = new List<SelectListItem>();

            foreach (var album in _dbContext.Albums)
            {
                var currentAlbum = _dbContext.Albums.Find(album.Id);
                var currentPerformer = _dbContext.Performers.Find(currentAlbum.PerformerId);
                resSelectList.Add(new SelectListItem()
                {
                    Value = currentAlbum.Id,
                    Text = currentAlbum.Name + " - "+currentPerformer.Name
                });
                if (selectedAlbumId == album.Id)
                {
                    resSelectList.Last().Selected = true;
                }
            }

            ViewData["AlbumId"] = resSelectList;

        }

    }



}

MusicWorld/Views/Performer/Create.cshtml
@model MusicWorld.Models.Performers.PerformersCreateViewModel

@{
    ViewData["Title"] = "Create performer";
}

<h1>Create new performer</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicWorld/Views/Performer/Delete.cshtml
@model MusicWorld.Models.Performers.PerformersViewModel

@{
    ViewData["Title"] = "DeletePerformer";
}

<h2>Are you sure you want to delete this performer?</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger font-weight-bold mr-3 p-2" />
        <a type="submit" asp-action="Index" class="btn btn-info p-2">Cancel</a>
    </form>
</div>

MusicWorld/Views/Performer/Details.cshtml
@model MusicWorld.Models.Performers.PerformersDetailViewModel

@{
    ViewData["Title"] = "DetailPerformer";
}

<h1>Personal performer information</h1>

<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PerformerInformation.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PerformerInformation.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PerformerInformation.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PerformerInformation.Description)
    </dd>
</dl>

<br />

<h1>Albums -> Songs</h1>
<hr />
<br />

<dl class="row">

    @foreach (var album in Model.Albums)
    {
        <dt class="col-sm-2">
            <a asp-controller="Album" asp-action="Details" asp-route-id="@album.AlbumInformation.Id">@album.AlbumInformation.Name</a>
            <br />
        </dt>
        <dd class="col-sm-10">
            @foreach (var song in album.Songs)
            {
                <p>
                    <a asp-controller="Song" asp-action="Details" asp-route-id="@song.Id">@song.Name</a>
                     (@song.Duration min)
                </p>
            }
        </dd>
    }
</dl>

<br />
<div>
    <a asp-action="Edit" asp-route-id="@Model.PerformerInformation.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MusicWorld/Views/Performer/Edit.cshtml
@model MusicWorld.Models.Performers.PerformersEditViewModel

@{
    ViewData["Title"] = "EditPerformer";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MusicWorld/Views/Performer/Index.cshtml
@model MusicWorld.Models.Performers.PerformersAllViewModel

@{
    ViewData["Title"] = "AllPerformers";
}

<h1>All performers</h1>
@if (this.User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create new performer</a>
    </p>
}

<form asp-action="Index">
    <div class="row">
        <div class="col-md-4">
            <input asp-for="SearchWord" placeholder="Search performer ..." class="form-control" />
        </div>
        <div class="col-md-1">
            <input type="submit" value="Search" class="btn btn-info" />
        </div>

    </div>
</form>

<br />

@if (Model.Performers != null && Model.Performers.Count != 0)
{

    <table class="table text-center">
        <thead>
            <tr>

                <th>
                    Name
                </th>
                <th>
                    Count of Albums
                </th>
                <th>
                    Count of Songs
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Performers)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AlbumsNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SongsNumber)
                    </td>



                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <br />
    <div class="text-center text-black-50 font-italic w-10" style="font:40px Arial">Nothing to display</div>
}